name: Build

on: push

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Build application
        run: make

      - name: Check codestyle
        run: git ls-files *.{cpp,h} | xargs clang-format -i --verbose && git diff --exit-code